apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: LoadBalancer
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
status:
  loadBalancer:
    ingress:
    - ip: 192.168.42.111
